# Generated by Django 6.0.6 on 2026-06-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Original price before discount (optional)'),
        ),
    ]
