# Generated by Django 6.0.3 on 2026-06-12 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('bicycle', 'Bicycle'), ('scooter', 'Scooter')], default='bike', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Boy',
                'verbose_name_plural': 'Delivery Boys',
            },
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='assigned', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('delivery_boy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='deliveryapp.deliveryboy')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='userapp.order')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
