# Generated by Django 6.0.6 on 2026-06-29 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_order_contact_name_order_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_failed', 'Payment Failed'), ('payment_successful', 'Payment Successful'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out for Delivery'), ('near_location', 'Near Location'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
    ]
