# Generated by Django 6.0.3 on 2026-08-06 12:24

import app_modules.userapp.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', app_modules.userapp.managers.CustomUserManager()),
            ],
        ),
    ]
